first
ClevertecFrontendLab/sprint1-TatianaPiskunova pull request #1
Opened 2023-01-30 21:24 UTC by TatianaPiskunova

2023-01-30 22:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675116753/content-window.png)

2023-01-31 06:56 UTC, klichkovskiy requested changes
Пересмотри скрины

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
свг импортируй как картинки. по всему коду

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +                <div className="bookCategory">Бизнес книги</div>
![image](https://user-images.githubusercontent.com/62481116/215686626-78c9afbf-9d82-4bd4-9054-d3cd59b846d6.png)
Сделай по макету

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +                        <button type="button" className="buttonInfoAboutBook">
![image](https://user-images.githubusercontent.com/62481116/215686697-35ec5c3e-8de0-4446-80f8-0f126055e353.png)
кнопка не по макету

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +                        <button type="button" className="buttonReview">
![image](https://user-images.githubusercontent.com/62481116/215686807-087f1dec-8f0d-410d-b5c3-302965fd01d8.png)
кнопка не по макету

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +                            <div className="textButtonReview">Oценить книгу</div>
а зачем внутри еще 1 див? там же только текст

2023-01-31 06:56 UTC, klichkovskiy commented on src/index.js
> +          <Route element={<Menu/>}/>
Лучшей практикой было бы использование Layout, чем вставлять компоненты каждый раз в код и при каждом переходе их рендерить

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/nav-list/nav-list.jsx
> +                <div className="textFilter">
![image](https://user-images.githubusercontent.com/62481116/215687662-ec6f1fe8-4cfa-40cd-9221-35446ca250e7.png)
Сделай по макету

2023-01-31 06:56 UTC, klichkovskiy commented on src/pages/menu/category/category.jsx
> +    categories.map(item=>item.id).forEach(element=>{
![image](https://user-images.githubusercontent.com/62481116/215687885-52322235-b49b-4264-a84b-96c1954facd4.png)
Все книги тоже должна быть активной при старте
Количество книг  сделай как в макете

2023-01-31 06:56 UTC, klichkovskiy commented on src/index.js
> +          <Route element={<Menu/>}/>
![image](https://user-images.githubusercontent.com/62481116/215688328-0bad420e-934a-4e5b-b47a-56c7c9499085.png)
Поправь кнопки. Я даже не могу найти где у тебя этот компонент в коде

2023-01-31 21:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675200886/content-window.png)

2023-01-31 21:42 UTC, klichkovskiy requested changes
Исправь. Перед тем как отправить повторно - перепроверь все!

2023-01-31 21:42 UTC, klichkovskiy commented on src/pages/header/header.jsx
> +        <header className="header">
Отступы сделай как в макете
![image](https://user-images.githubusercontent.com/62481116/215889524-9c9f64c3-d8dd-4bf2-85ab-04a2a501da04.png)

2023-01-31 21:42 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +                        <button type="button" className="buttonInfoAboutBook">Забронировать</button>
![image](https://user-images.githubusercontent.com/62481116/215889676-ee7e9662-b991-4fce-a73f-e69899e79fa5.png)
Сделай ВСЕ кнопки как в макете!!!

2023-01-31 21:42 UTC, klichkovskiy commented on src/pages/main/main-page.jsx
> +          <Menu/>
![image](https://user-images.githubusercontent.com/62481116/215889820-0954f924-c1c5-4dc8-ae78-b72df0869a0b.png)
Я же уже показывал эти ошибки. Перепроверь себя перед тем как отправлять в следующий раз.

2023-02-02 15:35 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaPiskunova/1675352136/content-window.png)

2023-02-02 15:53 UTC, klichkovskiy approved these changes

2023-02-02 17:07 UTC, merged